export enum TYPES {
  CONFIRMATION = 'CONFIRMATION',
  FETCH_STAR_WARS_REQUEST = 'FETCH_STAR_WARS_REQUEST',
  FETCH_STAR_WARS_PLANETS_REQUEST = 'FETCH_STAR_WARS_PLANETS_REQUEST',
  FETCH_STAR_WARS_SUCCESS = 'FETCH_STAR_WARS_SUCCESS',
  FETCH_STAR_WARS_PLANETS_SUCCESS = 'FETCH_STAR_WARS_PLANETS_SUCCESS'
}
